### Register
POST {{EXPO_PUBLIC_BASE_URL}}/auth/register
Content-Type: application/json

{
  "email": "example40@gmail.com",
  "full_name": "James Brown",
  "password": "password"
}

### Login
POST {{EXPO_PUBLIC_BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "example40@gmail.com",
  "password": "password"
}

# @lang=lua
> {%
local json = vim.json.decode(response.body)
client.global.set("token", json.token);
%}

### Profile
GET {{EXPO_PUBLIC_BASE_URL}}/profile/
Content-Type: application/json
Authorization: Bearer {{token}}

### Symptoms
POST {{EXPO_PUBLIC_BASE_URL}}/symptoms/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": 7,
  "condition":"PCOS",
  "symptoms":"Body weekness",
  "pain_level": 7,
  "mood":"moody",
  "cycle_day": 4,
  "notes":""
}

### Recommendations
GET {{EXPO_PUBLIC_BASE_URL}}/recommendations/11
Content-Type: application/json
Authorization: Bearer {{token}}
